'# typed: false
'# frozen_string_literal: true

'# This file was generated by GoReleaser. DO NOT EDIT.
class Nextdns < Formula
  desc "NextDNS DNS/53 to DoH Proxy"
  homepage "https://nextdns.io"
  version "1.32.3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nextdns/nextdns/releases/download/v1.32.3/nextdns_1.32.3_darwin_amd64.tar.gz"
      sha256 "1ee0c8a9c7eedf9fccc202b4b05ef06b5a803bd61a9e6c658f0e29114c41cdf2"
    end
    if Hardware::CPU.arm?
      url "https://github.com/nextdns/nextdns/releases/download/v1.32.3/nextdns_1.32.3_darwin_arm64.tar.gz"
      sha256 "1f2f2153771beed4abaeb9679c255b2dfc2a7459b2ee38668ac02bb897f8f1b0"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nextdns/nextdns/releases/download/v1.32.3/nextdns_1.32.3_linux_amd64.tar.gz"
      sha256 "ab959897c092b231a298f9dac8f7aea7c802dca41785715652ee585bd01c7013"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nextdns/nextdns/releases/download/v1.32.3/nextdns_1.32.3_linux_armv6.tar.gz"
      sha256 "42eeef0a1c2bb4b564731b751b267024f9f81687a6c2936c2eeee9c190e8d6df"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nextdns/nextdns/releases/download/v1.32.3/nextdns_1.32.3_linux_arm64.tar.gz"
      sha256 "c9f1592ca3f0ce64bbded2b5ff7e3e093004cde8a7014f5e12441f2279eb85dc"
    end
  end

  def install
    bin.install "nextdns"
  end

  def caveats; <<~EOS
    To install NextDNS, run the following command:
    sudo nextdns install --config <your_conf_id>
    Then setup your DNS manually to 127.0.0.1 or by running:
    sudo nextdns activate
  EOS
  end
end
