# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nextdns < Formula
  desc "NextDNS DNS/53 to DoH Proxy"
  homepage "https://nextdns.io"
  version "1.9.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/nextdns/nextdns/releases/download/v1.9.6/nextdns_1.9.6_darwin_amd64.tar.gz"
    sha256 "0890bfd543069e41b278c31458e571d396f4a9882ad6c25f87f1c6f7792ba554"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/nextdns/nextdns/releases/download/v1.9.6/nextdns_1.9.6_linux_amd64.tar.gz"
    sha256 "cbae6c30be379d1b04b63f93ff26d2ea54e77818f50814fa4322266c154c2531"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/nextdns/nextdns/releases/download/v1.9.6/nextdns_1.9.6_linux_armv6.tar.gz"
    sha256 "62cd1c32bf74b376be1f0ff97d856fac0116994874dc3ee32c8a5c09e3b4f9c4"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/nextdns/nextdns/releases/download/v1.9.6/nextdns_1.9.6_linux_arm64.tar.gz"
    sha256 "518c3c5c27d8f6926cf2b0e6418d30237578944bbf7a01d60ce8975ebcb71438"
  end

  def install
    bin.install "nextdns"
  end

  def caveats; <<~EOS
    To install NextDNS, run the following command:
    sudo nextdns install --config <your_conf_id>
    Then setup your DNS manually to 127.0.0.1 or by running:
    sudo nextdns activate
  EOS
  end
end
