# This file was generated by GoReleaser. DO NOT EDIT.
class Nextdns < Formula
  desc "NextDNS DNS/53 to DoH Proxy"
  homepage "https://nextdns.io"
  version "1.4.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/nextdns/nextdns/releases/download/v1.4.3/nextdns_1.4.3_darwin_amd64.tar.gz"
    sha256 "1d6c29c0c8174fb918038fe8774e1852e8939480987ea2e94d998cc58de209d4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/nextdns/nextdns/releases/download/v1.4.3/nextdns_1.4.3_linux_amd64.tar.gz"
      sha256 "cb7b08a0371929ab34601d97ef51e3e6270866f46845fcd0c00aee09932d4328"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nextdns/nextdns/releases/download/v1.4.3/nextdns_1.4.3_linux_arm64.tar.gz"
        sha256 "a9a0f74eb89e00d3bbdb44fd913578c648027e7e1bd78213f4e0156b7ee84b62"
      else
        url "https://github.com/nextdns/nextdns/releases/download/v1.4.3/nextdns_1.4.3_linux_armv6.tar.gz"
        sha256 "c359b6e84436c7d02717aff1d6cb74ed0a4800d7ccfb91a5fc9ce8fe8eef276e"
      end
    end
  end

  def install
    bin.install "nextdns"
  end

  def caveats; <<~EOS
    To install NextDNS, run the following command:
    sudo nextdns install --config <your_conf_id>
    Then setup your DNS manually to 127.0.0.1 or by running:
    sudo nextdns activate
  EOS
  end
end
